backend/config/routes.rb
Spree::Core::Engine.routes.draw do
  root :to => 'home#index'

  namespace :admin do
    get '/search/users', :to => "search#users", :as => :search_users

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :adjustments
    resources :zones
    resources :banners do
      member do
        post :dismiss
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
    end

    get '/variants/search', :to => "variants#search", :as => :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', :to => "option_values#destroy", :as => :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', :to => "product_properties#destroy", :as => :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :image_settings

    resources :orders, :except => [:show] do
      member do
        put :fire
        get :fire
        post :resend
        get :open_adjustments
        get :close_adjustments
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments do
        member do
          get :toggle_state
        end
      end
      resources :line_items
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      collection do
      	post :update_positions
      end
      member do
        get :get_children
      end
      resources :taxons
    end

    resources :taxons, :only => [] do
      collection do
        get :search
      end
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, :only => [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements
      collection do
        post :transfer_stock
      end
    end

    resources :stock_movements
    resources :stock_items, :only => [:create, :update, :destroy]
    resources :tax_rates
    resource  :tax_settings

    resources :trackers
    resources :payment_methods
    resource :mail_method, :only => [:edit, :update] do
      post :testmail, :on => :collection
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin
end

backend/app/controllers/spree/admin/products_controller.rb
module Spree
  module Admin
    class ProductsController < ResourceController
      helper 'spree/products'

      before_filter :load_data, :except => :index
      create.before :create_before
      update.before :update_before

      def show
        session[:return_to] ||= request.referer
        redirect_to( :action => :edit )
      end

      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def update
        if params[:product][:taxon_ids].present?
          params[:product][:taxon_ids] = params[:product][:taxon_ids].split(',')
        end
        if params[:product][:option_type_ids].present?
          params[:product][:option_type_ids] = params[:product][:option_type_ids].split(',')
        end
        super
      end

      def destroy
        @product = Product.find_by_permalink!(params[:id])
        @product.delete

        flash[:success] = Spree.t('notice_messages.product_deleted')

        respond_with(@product) do |format|
          format.html { redirect_to collection_url }
          format.js  { render_js_for_destroy }
        end
      end

      def clone
        @new = @product.duplicate

        if @new.save
          flash[:success] = Spree.t('notice_messages.product_cloned')
        else
          flash[:success] = Spree.t('notice_messages.product_not_cloned')
        end

        redirect_to edit_admin_product_url(@new)
      end

      def stock
        @variants = @product.variants
        @variants = [@product.master] if @variants.empty?
        @stock_locations = StockLocation.accessible_by(current_ability, :read)
      end

      protected

        def find_resource
          Product.find_by_permalink!(params[:id])
        end

        def location_after_save
          spree.edit_admin_product_url(@product)
        end

        def load_data
          @taxons = Taxon.order(:name)
          @option_types = OptionType.order(:name)
          @tax_categories = TaxCategory.order(:name)
          @shipping_categories = ShippingCategory.order(:name)
        end

        def collection
          return @collection if @collection.present?
          params[:q] ||= {}
          params[:q][:deleted_at_null] ||= "1"

          params[:q][:s] ||= "name asc"

          @search = super.ransack(params[:q])
          @collection = @search.result.
            group_by_products_id.
            includes(product_includes).
            page(params[:page]).
            per(Spree::Config[:admin_products_per_page])

          if params[:q][:s].include?("master_default_price_amount")
            # PostgreSQL compatibility
            @collection = @collection.group("spree_prices.amount")
          end
          @collection
        end

        def create_before
          return if params[:product][:prototype_id].blank?
          @prototype = Spree::Prototype.find(params[:product][:prototype_id])
        end

        def update_before
          # note: we only reset the product properties if we're receiving a post from the form on that tab
          return unless params[:clear_product_properties]
          params[:product] ||= {}
        end

        def product_includes
         [{:variants => [:images, {:option_values => :option_type}]}, {:master => [:images, :default_price]}]
        end

    end
  end
end

backend/app/helpers/spree/admin/products_helper.rb
module Spree
  module Admin
    module ProductsHelper
      def taxon_options_for(product)
        options = @taxons.map do |taxon|
          selected = product.taxons.include?(taxon)
          content_tag(:option,
                      :value    => taxon.id,
                      :selected => ('selected' if selected)) do
            (taxon.ancestors.pluck(:name) + [taxon.name]).join(" -> ")
          end
        end.join("").html_safe
      end

      def option_types_options_for(product)
        options = @option_types.map do |option_type|
          selected = product.option_types.include?(option_type)
          content_tag(:option,
                      :value    => option_type.id,
                      :selected => ('selected' if selected)) do
            option_type.name
          end
        end.join("").html_safe
      end
    end
  end
end

backend/app/views/spree/admin/products/_add_stock_form.html.erb
<%= form_for [:admin, Spree::StockMovement.new], url: admin_stock_items_path do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t(:add_stock_management) %></legend>

    <div data-hook="admin_stock_movements_form_fields" class="row">
      <div class="alpha two columns">
        <%= f.field_container :quantity do %>
          <%= f.label :quantity, Spree.t(:quantity) %>
          <%= f.number_field :quantity, class: 'fullwidth', value: 1 %>
        <% end %>
      </div>
      <div class="five columns">
        <%= f.field_container :stock_location do %>
          <%= label_tag :stock_location_id, Spree.t(:stock_location) %>
          <%= select_tag 'stock_location_id', options_from_collection_for_select(@stock_locations, :id, :name),
            class: 'select2 fullwidth' %>
        <% end %>
      </div>

      <div class="five columns omega">
        <%= f.field_container :variant_id do %>
          <%= label_tag 'variant_id', Spree.t(:variant) %>
          <%= select_tag 'variant_id', options_from_collection_for_select(@variants, :id, :sku),
            class: 'select2 fullwidth' %>
        <% end %>
      </div>
    </div>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t(:add_stock), 'icon-plus' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to_with_icon 'icon-remove', Spree.t('actions.cancel'), collection_url, :class => 'button' %>
    </div>
  </fieldset>
<% end %>

backend/app/views/spree/admin/products/_form.html.erb
<div data-hook="admin_product_form_fields">
  
  <div class="left eight columns alpha" data-hook="admin_product_form_left">    
    <%= f.field_container :name do %>
      <%= f.label :name, raw(Spree.t(:name) + content_tag(:span, ' *', :class => 'required')) %>
      <%= f.text_field :name, :class => 'fullwidth title' %>
      <%= f.error_message_on :name %>
    <% end %>

    <%= f.field_container :permalink do %>
      <%= f.label :permalink, raw(Spree.t(:permalink) + content_tag(:span, ' *',  :class => "required")) %>
      <%= f.text_field :permalink, :class => 'fullwidth title' %>
      <%= f.error_message_on :permalink %>
    <% end %>

    <%= f.field_container :description do %>
      <%= f.label :description, Spree.t(:description) %>
      <%= f.text_area :description, {:rows => "#{unless @product.has_variants? then '20' else '13' end}", :class => 'fullwidth'} %>
      <%= f.error_message_on :description %>
    <% end %>
  </div>

  <div class="right four columns omega" data-hook="admin_product_form_right">
    <%= f.field_container :price do %>
      <%= f.label :price, raw(Spree.t(:master_price) + content_tag(:span, ' *', :class => "required")) %>
      <%= f.text_field :price, :value => number_to_currency(@product.price, :unit => '') %>
      <%= f.error_message_on :price %>
    <% end %>

    <div class="alpha two columns">
      <%= f.field_container :cost_price do %>
        <%= f.label :cost_price, Spree.t(:cost_price) %>
        <%= f.text_field :cost_price, :value => number_to_currency(@product.cost_price, :unit => '') %>
        <%= f.error_message_on :cost_price %>
      <% end %>
    </div>
    <div class="omega two columns">
      <%= f.field_container :cost_currency do %>
        <%= f.label :cost_currency, Spree.t(:cost_currency) %>
        <%= f.text_field :cost_currency %>
        <%= f.error_message_on :cost_currency %>
      <% end %>
    </div>

    <div class="clear"></div>

    <%= f.field_container :available_on do %>
      <%= f.label :available_on, Spree.t(:available_on) %>
      <%= f.error_message_on :available_on %>
      <%= f.text_field :available_on, :value => datepicker_field_value(@product.available_on), :class => 'datepicker' %>
    <% end %>

    <% unless @product.has_variants? %>
      <%= f.field_container :sku do %>
        <%= f.label :sku, Spree.t(:sku) %>
        <%= f.text_field :sku, :size => 16 %>
      <% end %>

      <ul id="shipping_specs">
        <li id="shipping_specs_weight_field" class="field alpha two columns">
          <%= f.label :weight, Spree.t(:weight) %>
          <%= f.text_field :weight, :size => 4 %>
        </li>
        <li id="shipping_specs_height_field" class="field omega two columns">
          <%= f.label :height, Spree.t(:height) %>
          <%= f.text_field :height, :size => 4 %>
        </li>
        <li id="shipping_specs_width_field" class="field alpha two columns">
          <%= f.label :width, Spree.t(:width) %>
          <%= f.text_field :width, :size => 4 %>
        </li>
        <li id="shipping_specs_depth_field" class="field omega two columns">
          <%= f.label :depth, Spree.t(:depth) %>
          <%= f.text_field :depth, :size => 4 %>
        </li>
      </ul>
    <% end %>

    <%= f.field_container :shipping_categories do %>
      <%= f.label :shipping_category_id, Spree.t(:shipping_categories) %>
      <%= f.collection_select(:shipping_category_id, @shipping_categories, :id, :name, { :include_blank => 'None' }, { :class => 'select2' }) %>
      <%= f.error_message_on :shipping_category %>
    <% end %>

    <%= f.field_container :tax_category do %>
      <%= f.label :tax_category_id, Spree.t(:tax_category) %>
      <%= f.collection_select(:tax_category_id, @tax_categories, :id, :name, { :include_blank => 'None' }, { :class => 'select2' }) %>
      <%= f.error_message_on :tax_category %>
    <% end %>
  </div>

  <div class="twelve columns alpha omega">
    <%= f.field_container :taxons do %>
      <%= f.label :taxon_ids, Spree.t(:taxons) %><br />
      <%= f.hidden_field :taxon_ids, :value => @product.taxon_ids.join(',') %>
    <% end %>

    <%= f.field_container :option_types do %>
      <%= f.label :option_type_ids, Spree.t(:option_types) %>
      <%= f.hidden_field :option_type_ids, :value => @product.option_type_ids.join(',') %>
    <% end %>
  </div>

  <!-- <h2><%= Spree.t(:metadata) %></h2> -->
  <div data-hook="admin_product_form_meta" class="alpha omega twelve columns">
    <%= f.field_container :meta_keywords do %>
      <%= f.label :meta_keywords, Spree.t(:meta_keywords) %>
      <%= f.text_field :meta_keywords, :class => 'fullwidth' %>
    <% end %>

    <%= f.field_container :meta_description do %>
      <%= f.label :meta_description, Spree.t(:meta_description) %>
      <%= f.text_field :meta_description, :class => 'fullwidth' %>
    <% end %>
  </div>

  <div class="clear"></div>

  <div data-hook="admin_product_form_additional_fields"></div>

  <div class="clear"></div>
</div>

<% unless Rails.env.test? %>
  <script>
  $('.select2-container').css({width: '20em'})
  </script>
<% end %>

backend/app/views/spree/admin/products/_properties_form.erb
<% content_for :page_title do %>
  <%= Spree.t(:properties) %>
<% end %>

<% f.fields_for :product_properties do |properties_form| %>
    <div data-hook="value">
      <%= properties_form.label :value, properties_form.object.property.presentation %><br />
      <%= properties_form.text_field :value %>
    </div>
<% end %>

backend/app/views/spree/admin/products/edit.html.erb
<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_products_list), session[:return_to] || admin_products_url, :icon => 'icon-arrow-left' %></li>
  <li id="new_product_link">
    <%= button_link_to Spree.t(:new_product), new_object_url, { :icon => 'icon-plus', :id => 'admin_new_product' } %>
  </li>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Product Details' } %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @product } %>

<%= form_for [:admin, @product], :method => :put, :html => { :multipart => true } do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

backend/app/views/spree/admin/products/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_products) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_product_link">
    <%= button_link_to Spree.t(:new_product), new_object_url, { :remote => true, :icon => 'icon-plus', :id => 'admin_new_product' } %>
  </li>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_products_sidebar">

    <%= search_form_for [:admin, @search] do |f| %>

        <%- locals = {:f => f} %>

        <div data-hook="admin_products_index_search">
          <div class="alpha nine columns">
            <div class="field">
              <%= f.label :name_cont, Spree.t(:name) %>
              <%= f.text_field :name_cont, :size => 15 %>
            </div>
          </div>
          <div class="four columns">
            <div class="field">
              <%= f.label :variants_including_master_sku_cont, Spree.t(:sku) %>
              <%= f.text_field :variants_including_master_sku_cont, :size => 15 %>
            </div>
          </div>
          <div class="three columns omega">
            <div class="field checkbox">
              <label>
                <%= f.check_box :deleted_at_null, {:checked => params[:q][:deleted_at_null].blank?}, '', '1' %>
                <%= Spree.t(:show_deleted) %>
              </label>
            </div>
          </div>
        </div>

        <div class="clear"></div>

        <div class="form-buttons actions filter-actions" data-hook="admin_products_index_search_buttons">
          <%= button Spree.t(:search), 'icon-search' %>
        </div>
    <% end %>
  </div>
<% end %>

<div id="new_product_wrapper" data-hook></div>

<%= paginate @collection %>

<% if @collection.any? %>
  <table class="index" id="listing_products">
    <colgroup>
       <col style="width: 15%;">
       <col style="width: 10%;">
       <col style="width: 48%;">
       <col style="width: 10%;">
       <col style="width: 17%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= Spree.t(:sku) %></th>
        <th colspan="2"><%= sort_link @search,:name, Spree.t(:name), { :default_order => "desc" }, {:title => 'admin_products_listing_name_title'} %></th>
        <th><%= sort_link @search,:master_default_price_amount, Spree.t(:master_price), {}, {:title => 'admin_products_listing_price_title'} %></th>
        <th data-hook="admin_products_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |product| %>
          <tr <%= "style='color: red;'" if product.deleted? %> id="<%= spree_dom_id product %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
            <td class="align-center"><%= product.sku rescue '' %></td>
            <td class="align-center"><%= mini_image(product) %></td>
            <td><%= link_to product.try(:name), edit_admin_product_path(product) %></td>
            <td class="align-center"><%= product.display_price.to_html rescue '' %></td>
            <td class="actions" data-hook="admin_products_index_row_actions">
              <%= link_to_edit product, :no_text => true, :class => 'edit' unless product.deleted? %>
              &nbsp;
              <%= link_to_clone product, :no_text => true, :class => 'clone' %>
              &nbsp;
              <%= link_to_delete product, :no_text => true unless product.deleted? %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= Spree.t(:no_results) %>
  </div>
<% end %>

<%= paginate @collection %>

backend/app/views/spree/admin/products/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @product } %>

<%= form_for [:admin, @product], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_product">

    <legend align="center"><%= Spree.t(:new_product) %></legend>

    <%= f.field_container :name do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span><br />
      <%= f.text_field :name, :class => 'fullwidth title' %>
      <%= f.error_message_on :name %>
    <% end %>

    <div data-hook="new_product_attrs" class="row">
      <% unless @product.has_variants? %>
        <div class="alpha four columns">
          <%= f.field_container :sku do %>
            <%= f.label :sku, Spree.t(:sku) %><br />
            <%= f.text_field :sku, :size => 16, :class => 'fullwidth' %>
            <%= f.error_message_on :sku %>
          <% end %>
        </div>
      <% end %>

      <div class="four columns">
        <%= f.field_container :prototype do %>
          <%= f.label :prototype_id, Spree.t(:prototype) %><br />
          <%= f.collection_select :prototype_id, Spree::Prototype.all, :id, :name, {:include_blank => true}, {:class => 'select2 fullwidth'} %>
        <% end %>
      </div>

      <div class="four columns">
        <%= f.field_container :price do %>
          <%= f.label :price, Spree.t(:master_price) %> <span class="required">*</span><br />
          <%= f.text_field :price, :class => 'fullwidth' %>
          <%= f.error_message_on :price %>
        <% end %>
      </div>

      <div class="omega four columns">
        <%= f.field_container :available_on do %>
          <%= f.label :available_on, Spree.t(:available_on) %>
          <%= f.error_message_on :available_on %>
          <%= f.text_field :available_on, :class => 'datepicker fullwidth' %>
        <% end %>
      </div>

    </div>

    <div class="clearfix" data-hook="product-from-prototype" id="product-from-prototype">
      <%= render :file => 'spree/admin/prototypes/show' if @prototype %>
    </div>

    <%= render :partial => 'spree/admin/shared/new_resource_links' %>

  </fieldset>
<% end %>

<script type="text/javascript">
//<![CDATA[
  (function($){
    var base_url = "<%= admin_prototypes_url %>";
    var prototype_select = $('#product_prototype_id');
    prototype_select.change(function() {
      var id = prototype_select.val();
      if (id.length) {
        var url = new Uri(base_url);
        url.setPath(url.path() + '/' + id);
        $('#product-from-prototype').load(url.toString());
      } else {
        $('#product-from-prototype').empty();
      }
    })
    if (prototype_select.html() == "") {
      prototype_select.change();
    }
  })(jQuery);
//]]>
</script>

backend/app/views/spree/admin/products/new.js.erb
$("#new_product_wrapper").html('<%= escape_javascript(render :template => "spree/admin/products/new", :formats => [:html], :handlers => [:erb]) %>');
handle_date_picker_fields();
<% unless Rails.env.test? %>
  $('.select2').select2();
<% end %>
$("#table-filter").hide();
$("#admin_new_product").parent().hide();

backend/app/views/spree/admin/products/stock.html.erb
<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_products_list), session[:return_to] || admin_products_url, :icon => 'icon-arrow-left' %></li>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Stock Management' } %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @product } %>

<div id="add_stock_form">
  <%= render 'add_stock_form' %>
</div>

<table class="index" id="listing_product_stock">
  <colgroup>
    <col style="width: 25%" />
    <col style="width: 25%" />
    <col style="width: 25%" />
    <col style="width: 25%" />
  </colgroup>
  <thead>
    <tr data-hook="admin_product_stock_management_index_headers">
      <th><%= Spree.t(:variant) %></th>
      <th colspan="3"><%= Spree.t(:stock_location_info) %></th>
    </tr>
  </thead>
  <tbody>
    <% @variants.each do |variant| %>
      <% if variant.stock_items.present? %>
        <tr id="<%= spree_dom_id variant %>" data-hook="admin_product_stock_management_index_rows" class="<%= cycle('odd', 'even') %>">
          <td class="align-center">
            <%= variant.sku %>
            <br>
            <% if variant.images.present? %>
              <%= image_tag variant.images.first.attachment.url(:mini) %>
            <% end %>
          </td>
          <td colspan="4" class="stock_location_info">
            <table>
              <colgroup>
                <col style="width: 40%" />
                <col style="width: 20%" />
                <col style="width: 20%" />
                <col style="width: 20%" />
              </colgroup>
              <thead>
                <th><%= Spree.t(:stock_location) %></th>
                <th><%= Spree.t(:count_on_hand) %></th>
                <th><%= Spree.t(:backorderable) %></th>
                <th></th>
              </thead>
              <tbody>
                <% variant.stock_items.each do |item| %>
                  <% next unless @stock_locations.include?(item.stock_location) %>

                  <tr id="stock-item-<%= item.id %>" class="<%= cycle('odd', 'even', :name => 'stock_locations')%>">
                    <td><%= item.stock_location.name %></td>
                    <td class="align-center"><%= item.count_on_hand %></td>
                    <td class="align-center">
                      <%= form_tag admin_stock_item_path(item), method: :put, class: 'toggle_stock_item_backorderable' do %>
                        <%= check_box_tag 'stock_item[backorderable]', true,
                              item.backorderable?,
                              class: 'stock_item_backorderable',
                              id: "stock_item_backorderable_#{item.stock_location.id}" %>
                      <% end %>
                    </td>
                    <td class="align-center">
                      <%= link_to "", [:admin, item], method: :delete, remote: true,
                        confirm: Spree.t(:are_you_sure), class: "icon_link with-tip icon-trash" %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </td>
          <% reset_cycle("stock_locations") %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>