backend/config/routes.rb
Spree::Core::Engine.routes.draw do
  root :to => 'home#index'

  namespace :admin do
    get '/search/users', :to => "search#users", :as => :search_users

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :adjustments
    resources :zones
    resources :banners do
      member do
        post :dismiss
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
    end

    get '/variants/search', :to => "variants#search", :as => :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', :to => "option_values#destroy", :as => :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', :to => "product_properties#destroy", :as => :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :image_settings

    resources :orders, :except => [:show] do
      member do
        put :fire
        get :fire
        post :resend
        get :open_adjustments
        get :close_adjustments
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments do
        member do
          get :toggle_state
        end
      end
      resources :line_items
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      collection do
      	post :update_positions
      end
      member do
        get :get_children
      end
      resources :taxons
    end

    resources :taxons, :only => [] do
      collection do
        get :search
      end
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, :only => [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements
      collection do
        post :transfer_stock
      end
    end

    resources :stock_movements
    resources :stock_items, :only => [:create, :update, :destroy]
    resources :tax_rates
    resource  :tax_settings

    resources :trackers
    resources :payment_methods
    resource :mail_method, :only => [:edit, :update] do
      post :testmail, :on => :collection
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin
end

backend/app/controllers/spree/admin/adjustments_controller.rb
module Spree
  module Admin
    class AdjustmentsController < ResourceController
      belongs_to 'spree/order', :find_by => :number
      destroy.after :reload_order

      def toggle_state
        redirect_to admin_order_adjustments_path(@order) if @adjustment.finalized?

        if @adjustment.immutable?
          @adjustment.fire_state_event(:open)
          flash[:success] = Spree.t(:adjustment_successfully_opened)
        else
          @adjustment.fire_state_event(:close)
          flash[:success] = Spree.t(:adjustment_successfully_closed)
        end
        redirect_to admin_order_adjustments_path(@order)
      end

      private
      def reload_order
        @order.reload
      end

      def collection
        parent.adjustments.eligible
      end
    end
  end
end

backend/app/views/spree/admin/adjustments/_adjustments_table.html.erb
<table class="index" data-hook="adjustments">
  <thead data-hook="adjustmment_head">
    <tr>
      <th><%= "#{Spree.t('date')}/#{Spree.t('time')}" %></th>
      <th><%= Spree.t(:description) %></th>
      <th><%= Spree.t(:amount) %></th>
      <th><%= Spree.t(:state) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @collection.each do |adjustment|
         @edit_url = edit_admin_order_adjustment_path(@order, adjustment)
         @delete_url = admin_order_adjustment_path(@order, adjustment)
    %>
      <tr id="<%= spree_dom_id(adjustment) %>" data-hook="adjustment_row" class="<%= cycle('odd', 'even')%>">
        <td class="align-center"><%= pretty_time(adjustment.created_at) %></td>
        <td class="align-center"><%= adjustment.label %></td>
        <td class="align-center"><%= adjustment.display_amount.to_html %></td>
        <td class="align-center"><%= adjustment_state(adjustment) %></td>
        <td class='actions'>
          <%= link_to_edit adjustment, :no_text => true %>
          <%= link_to_delete adjustment, :no_text => true %>
          <%= link_to_toggle_adjustment_state @order, adjustment, :no_text => true %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td class="align-center" colspan='4'>
        <%= button_to Spree.t(:open_all_adjustments), open_adjustments_admin_order_path(@order), :method => :get %>&nbsp;
        <%= button_to Spree.t(:close_all_adjustments), close_adjustments_admin_order_path(@order), :method => :get %>
      </td>
      <td class='actions'>&nbsp;</td>
    </tr>
  </tbody>
</table>

backend/app/views/spree/admin/adjustments/_form.html.erb
<div data-hook="admin_adjustment_form_fields" class="row">
  <div class="alpha three columns">
    <%= f.field_container :amount do %>
      <%= f.label :amount, raw(Spree.t(:amount) + content_tag(:span, " *", :class => "required")) %>
      <%= text_field :adjustment, :amount, :class => 'fullwidth' %>
      <%= f.error_message_on :amount %>
    <% end %>
  </div>
  <div class="omega nine columns">
    <%= f.field_container :label do %>
      <%= f.label :label, raw(Spree.t(:description) + content_tag(:span, " *", :class => "required")) %>
      <%= text_field :adjustment, :label, :class => 'fullwidth' %>
      <%= f.error_message_on :label %>
    <% end %>
  </div>
</div>

backend/app/views/spree/admin/adjustments/edit.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Adjustments' } %>

<% content_for :page_title do %>
  <i class="icon-arrow-right"></i> <%= Spree.t(:edit) %> <%= Spree.t(:adjustment) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_adjustments_list), spree.admin_order_adjustments_url(@order), :icon => 'icon-arrow-left' %></li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @adjustment } %>
<%= form_for @adjustment, :url => admin_order_adjustment_path(@order, @adjustment), :method => :put do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div class="filter-actions actions" data-hook="buttons">
      <%= button Spree.t(:continue), 'icon-arrow-right' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to_with_icon 'icon-remove', Spree.t('actions.cancel'), admin_order_adjustments_url(@order), :class => 'button' %>
    </div>
  </fieldset>
<% end %>

backend/app/views/spree/admin/adjustments/index.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Adjustments' } %>

<% content_for :page_title do %>
   <i class="icon-arrow-right"></i> <%= Spree.t(:adjustments) %>
<% end %>

<% content_for :page_actions do %>  
  <li><%= button_link_to Spree.t(:new_adjustment), new_admin_order_adjustment_url(@order), :icon => 'icon-plus' %></li>
  <li><%= button_link_to Spree.t(:back_to_orders_list), admin_orders_path, :icon => 'icon-arrow-left' %></li>
<% end %>

<%= render :partial => 'adjustments_table' %>

<%= button_link_to Spree.t(:continue), @order.cart? ? new_admin_order_payment_url(@order) : admin_orders_url, :icon => 'icon-arrow-right' %>

backend/app/views/spree/admin/adjustments/new.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Adjustments' } %>

<% content_for :page_title do %>
  <i class="icon-arrow-right"></i> <%= Spree.t(:new_adjustment) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_adjustments_list), spree.admin_order_adjustments_url(@order), :icon => 'icon-arrow-left' %></li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @adjustment } %>

<%= form_for @adjustment, :url => admin_order_adjustments_path do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div class="filter-actions actions" data-hook="buttons">
      <%= button Spree.t(:continue), 'icon-arrow-right' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), admin_order_adjustments_url(@order), :icon => 'icon-remove' %>
    </div>
  </fieldset>
<% end %>